<?php

/**
 * @file
 * Contains install and update functions for Linked Field.
 */

/**
 * Implements hook_enable().
 */
function linked_field_enable() {
  // We have to change the weight so we run at last.
  db_update('system')
    ->fields(array('weight' => '100'))
    ->condition('name', 'linked_field')
    ->execute();
}

/**
 * Implements hook_update_last_removed().
 */
function linked_field_update_last_removed() {
  return 7006;
}
